[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tic_tac_toe = "6WmnboLMNbXwnx2FvjjuowfXqufjjsnP1ojgGQdBcPzK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha"
