name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.0'

    - name: Install dependencies
      working-directory: ./front-end
      run: yarn install

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Build frontend
      working-directory: ./front-end
      run: yarn build

    - name: Deploy to Firebase Hosting
      working-directory: ./front-end
      run: firebase deploy --only hosting --project solana-tic-tac-toe
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
